browser_name=Firefox
app.dev.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
app.stage.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login

#QA Environment details

app.qa.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
app.qa.username=Admin
app.qa.password=admin123


#DEV Environment Details
app.qa.url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
app.qa.username=Admin
app.qa.password=admin123
