username = "//input[@name="username"]"
password = "//input[@name="password"]"
signInBtn = "//button[@type="submit"]"
pimMenu = "//ul[@class="oxd-main-menu"]/li[2]"
addEmployeeBtn = "//nav[@class="oxd-topbar-body-nav"]/ul/li[3]"
firstName = "//input[@name="firstName"]"
lastName = "//input[@name="lastName"]"
empId = "//label[contains(text(),'Employee Id')]/parent::div/following-sibling::div/input"
empIdErrorMsg = "//span[contains(@class,'error')]"
submitBtn = "//button[@type="submit"]"
firstNameTxtBx = "//div[@class="oxd-form-row"]/div/div[1]/descendant::input"